image:
  repository: ghcr.io/nikhith-kudumula/f1-streaming-producer
  tag: latest
  pullPolicy: IfNotPresent

kafka:
  bootstrapServers: f1-kafka-kafka-bootstrap.f1-streaming.svc.cluster.local:9092

replay:
  sessionKey: "9161"
  speed: "2.0"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
