image:
  repository: ghcr.io/nikhith-kudumula/f1-streaming-flink-jobs
  tag: latest

kafka:
  bootstrapServers: f1-kafka-kafka-bootstrap.f1-streaming.svc.cluster.local:9092

flink:
  version: "1.19"
  image: flink:1.19

jobs:
  leaderboard:
    enabled: true
    mainClass: com.f1streaming.flink.leaderboard.LeaderboardJob
    parallelism: 1
    taskManager:
      replicas: 1
      resource:
        memory: "1024m"
        cpu: 1

  enrichment:
    enabled: true
    mainClass: com.f1streaming.flink.enrichment.LapEnrichmentJob
    parallelism: 1
    taskManager:
      replicas: 1
      resource:
        memory: "1024m"
        cpu: 1

  alerts:
    enabled: true
    mainClass: com.f1streaming.flink.alerts.RaceAlertsJob
    parallelism: 1
    taskManager:
      replicas: 1
      resource:
        memory: "512m"
        cpu: 0.5
